### ISSUE TITLE
building errors

### ISSUE THREAD

**Issue by JQ-9527** [Particles-Research/Force_Chain_Finder_Public#10]
my system is Ubuntu20.04 
when I run : cmake .. 
it reports following errors:
```
-- pybind11 v2.13.0 dev1
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- VTK_VERSION: 9.3.0
-- Configuring done
CMake Error at src/pybind/tools/pybind11Tools.cmake:181 (add_library):
  Cannot find source file:

    ./src/pybind/userinterface.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:39 (pybind11_add_module)


CMake Error at src/pybind/tools/pybind11Tools.cmake:181 (add_library):
  No SOURCES given to target: forcechain
Call Stack (most recent call first):
  CMakeLists.txt:39 (pybind11_add_module)


CMake Generate step failed.  Build files cannot be regenerated correctly.

```
Actually, there is no 'userinterface.cpp' in the folder. Please tell me what is the problem. Thanks.

**Comment by vikaskok** [comment]
I agree.
`pybind` directory is missing inside the `src` directory.
As a result, compilation of the code is not possible currently.

**Comment by sihaeri** [comment]
Hi,
`Eigen` and `pybind` are external dependencies and are intentionally not included with this distribution. Please refer to the README file for more information about this.

**Comment by sihaeri** [comment]
Hi,
`Eigen` and `pybind` are external dependencies and are intentionally not included with this distribution. Please refer to the README file for more information about this.
